### ISSUE TITLE
Avertissement passage en négatif

### ISSUE THREAD

**Issue by NTag** [BinetReseau/chocapix-client#1]
Plus de mail lors du passage en négatif, ça se fait à chaque fois sous nos yeux vu qu'on est en train de logguer (ou bien peut-être garder le mail si on passe en négatif à cause d'une bouffe à plusieurs par exemple et qu'on n'est donc pas connecté).
Mais plutôt un effet genre agrandissement du solde, petite notification, un truc quoi.

**Comment by tizot** [comment]
Un mail quand on reçoit des agios par exemple ? (ce déterrage de topic quand même ^^)
