### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by NTag** [BinetReseau/chocapix-client#2]
Afficher des notifications (à la Facebook) plutôt que des mails pour avertir les respos-bars ou un utilisateur de qqch.

**Comment by NTag** [comment]
Pas sûr qu'on le garde ça si ? Plutôt des mails mais pour des choses utiles (pas le passage en négatif typiquement). Mais la réception d'amende ça a été fait :) .

**Comment by tizot** [comment]
Pour les notifications, il y avait ça, et puis éventuellement les trucs qui concernent l'espace root (demande de correction, demande d'être respo bar, etc.). Mais ça peut passer par mail aussi.

**Comment by Nadrieril** [comment]
La notification d'avoir été inclus dans une bouffe à plusieurs me paraît importante mais passe pas trop par mail

**Comment by tizot** [comment]
On peut faire comme pour les news, et la colorer pendant un temps dans l'historique de la personne pour qu'elle le remarque (par exemple, si la bouffe a été loguée après la dernière connexion)
Il n'y a rien de neuf à mettre en place comme ça en plus ^^

**Comment by Nadrieril** [comment]
:+1:

**Comment by tizot** [comment]
Pour implémenter ça, j'ai une question : comment on récupère la date de dernière connexion d'un User ? J'ai l'impression que le champ "last_login" de l'objet User n'est pas correctement mis à jour...
